name: CI/CD

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: clumpapp/clump-fe

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-web:
    name: Build web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
        
      - name: Build script
        run: ./build.sh

      - name: GH Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          # Newline-delimited list of path globs for asset files to upload
          files:
            ./build/web/*
